# Copyright OpenSearch Contributors
# SPDX-License-Identifier: Apache-2.0

# The OpenSearch Contributors require contributions made to
# this file be licensed under the Apache-2.0 license or a
# compatible open source license.


[tool.black]
line-length = 160
target-version = ['py37']

[tool.isort]
profile = "black"
line_length = 160

[tool.mypy]
python_version = 3.7
disallow_untyped_defs = true
warn_return_any = true
warn_unused_configs = true
strict_optional = false
show_error_codes = true
ignore_missing_imports = true