---
name: License Header Checker

on: [push, pull_request]

jobs:
  license-header-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.1.3"

      - name: Check License
        run: deno run --allow-read https://deno.land/x/license_checker@v3.1.4/main.ts
      # - name: Add License Header
      #   uses: kt3k/license_checker@v1.0.6

      