---
name: manifests

on:
  push:
  pull_request:
    paths:
      - 'manifests/**/*.yml'
      - '!manifests/templates/**/'
  schedule:
    - cron: 0 0 * * *

jobs:
  list-changed-manifests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get changed manifest files
        uses: tj-actions/changed-files@v5
        id: changed-files
        with:
          filepaths: |
            manifests/**/*.yml
            manifests/templates/**/
      - name: Set unique changed manifests as matrix
        id: set-matrix
        run: echo "::set-output name=matrix::${{ steps.changed-files.outputs.files }}"

  manifest-checks-jdk11:
    needs: list-manifests11
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9
      JDK_VERSION: 11
    strategy:
      matrix:
        manifest: ${{ fromJson(needs.list-changed-manifests.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Set Up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_VERSION }}
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Pipenv and Dependencies
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: OpenSearch Manifests
        run: |-
          ./ci.sh ${{ matrix.manifest }} --snapshot

  manifest-checks-jdk17:
    needs: list-manifests17
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9
      JDK_VERSION: 17
    strategy:
      matrix:
        manifest: ${{ fromJson(needs.list-changed-manifests.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Set Up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_VERSION }}
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Pipenv and Dependencies
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: OpenSearch Manifests
        run: |-
          ./ci.sh ${{ matrix.manifest }} --snapshot
