---
name: Update Release Refs

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New version number'
        required: true

jobs:
  update_tags_and_create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Update Tags
        run: |
          python .github/workflows/update_release_refs.py "${{ github.workspace }}/manifests/${{ inputs.new_version }}"

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git remote set-url origin https://github.com/hitenshKharva/opensearch-build.git
          git config --global user.email "kharva.hitensh11@gmail.com"
          git config --global user.name "hitenshKharva"
          git checkout -b update_manifests
          git add .
          git commit -s -m "Update tags to ${{ inputs.new_version }}"
          git push origin update_manifests --force
          gh pr create --title '[AUTO] Update manifests refs to tags' --body 'Testing' -H update_manifest -B main
